theme: jekyll-theme-minimal
description: I'm a Data Scientist focused on more general types of skills. I work at Algorithia and help grow the company through data focused stuff.
title: Justin's Stuff
description: description
